Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,36 +2,94 @@ version: 2.1
 jobs:
   build:
     docker:
-      - image: fr3akyphantom/droid-builder:latest
+      - image: fr3akyphantom/droid-builder:edge
     environment:
-      # MANIFEST_BR: '9.0' # Optional: State SHRP Manifest Branch. i.e., '9.0' or other
-      VENDOR: 'Cherry_Mobile' # State Product Vendor or Manufacturer
-      CODENAME: 'X930' # Device Codename
-      # GitHubMail: '' # Enter GitHub User EMail Address
-      # GitHubName: '' # Enter GitHub Username
-      # Add the following Token in encrypted form inside CircleCI
-      # GITHUB_TOKEN: '' # GitHub OAuth Token, for release
-      EXTRA_CMD: "cd bootable/recovery; patch -p1 < ../../device/${VENDOR}/${CODENAME}/patches/bootable/recovery/*.patch || true; cd ../.."
-      Device_Tree: 'https://github.com/loveleyz/X930' # The Full URL of DT
-      BUILDTYPE: 'userdebug' # Set as eng or userdebug
-      VER: '2.2'
-    working_directory: /home/builder/shrp/
+      # GitHubMail: "" # Git User Email Address
+      # GitHubName: "" # Git Username
+      # GITHUB_TOKEN: '' # MUST BE SECRET & PUT IN CIRCLECI PROJECT ENV VARS
+      VENDOR: 'Cherry_Mobile' # MANDATORY
+      CODENAME: 'X930' # MANDATORY
+      FLAVOR: 'userdebug' # MANDATORY
+    working_directory: /home/builder/android
     steps:
-      # - checkout
       - run:
-          name: Create a keep-alive shell
+          name: AIO Build
           command: |
-            cat \<< EOF > act.sh
-            #!/bin/bash
-            while true; do
-              echo -e "\n" && sleep 300
-            done
+            # SANITY CHECKS
+            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
+            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
+            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
+            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
+            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
+            if [[ -z $FLAVOR ]]; then echo -e "Set as 'eng' or 'userdebug'." && exit 1; fi
+            # Set GitAuth Infos"
+            git config --global user.email $GitHubMail
+            git config --global user.name $GitHubName
+            git config --global credential.helper store
+            git config --global color.ui true
+            
+            cd /home/builder/android
+            
+            echo -e "Initializing minimal manifest repo sync..."
+            repo init -q -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0 --depth 1
+            
+            echo -e "\nRemoving Unimportant Darwin-specific Files from syncing"
+            cd .repo/manifests
+            find . -type f -name '*.xml' | xargs sed -i '/darwin/d'
+            git commit -a -m "Magic" || true
+            cd ../ && sed -i '/darwin/d' manifest.xml && cd ../
+            
+            # Local manifests. Some builds fail if the file path does not exist.
+            mkdir -p .repo/local_manifests && cat \<<EOF > .repo/local_manifests/X930.xml
+            <?xml version="1.0" encoding="UTF-8"?>
+            <manifest>
+            <project path="device/Cherry_Mobile/X930" name="loveleyz/X930" revision="master" remote="github" />
+            </manifest>
             EOF
-            chmod a+x act.sh
-      - run:
-          name: Get Script and Execute Build
-          command: |
-            wget -q "https://gist.github.com/rokibhasansagar/bf1e94f9e7426650bcbbf16506511f25/raw/script.sh"
-            chmod a+x script.sh
-            # Run script along with keep-alive shell
-            ./act.sh & ./script.sh
+            
+            repo sync -c -q --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
+            
+            rm -rf bootable/recovery
+            git clone --quiet --progress https://github.com/PeterCxy/android_bootable_recovery -b android-9.0 --single-branch bootable/recovery
+            
+            # Unshallow vendor_omni
+            repo forall vendor/omni -c "git fetch --unshallow omnirom android-9.0"
+            # Retain "roomservice: Do not overwrite existing repositories"
+            repo forall vendor/omni -c "git revert 718f4c2fd6890f5eaa2d4972b1c3f3f582b5da47 -Xtheirs --no-edit --no-commit"
+            # Retain "roomservice: Do not overwrite existing devices"
+            repo forall vendor/omni -c "git revert 380d19cea2857d5901d7e7163f65ccc66d7bbad7 -Xtheirs --no-edit --no-commit"
+            # Add those retains into local commit
+            repo forall vendor/omni -c "git commit -m 'Fix Build from forked/personal repos'"
+            echo -e "\nPreparing Delicious Lunch..."
+            export ALLOW_MISSING_DEPENDENCIES=true
+            source build/envsetup.sh
+            lunch omni_X930-eng
+            
+            # Keep the whole .repo/manifests folder
+            cp -a .repo/manifests $(pwd)/
+            echo "Cleaning up the .repo folder to slim down the build system"
+            rm -rf .repo
+            mkdir -p .repo && mv manifests .repo/ && ln -s .repo/manifests/default.xml .repo/manifest.xml
+            
+            export nowTime=$(date +%Y%m%d-%H%M)
+            echo -e "\nBuilding Started, Please wait patiently...\n"
+            make -j$(nproc --all) recoveryimage
+            echo "Ready to Deploy"
+            mkdir upload
+            export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
+            cp out/target/product/${CODENAME}/recovery.img upload/TWRP-${version}-${CODENAME}-$nowTime-Unofficial.img
+            cp out/target/product/${CODENAME}/*.img upload/
+            cp out/target/product/${CODENAME}/ramdisk* upload/
+            ls -lA upload/
+            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Latest TWRP Release for $(echo $CODENAME)" -b "TWRP $(echo $version)" -delete twrp_v${version} upload/
+workflows:
+  version: 2
+  build_and_test:
+    jobs:
+      - build:
+        filters:
+            branches:
+              only: 'master'
+            context: personal-envs
+          # if you are copy-pasting this script,
+          # set $GitHubMail, $GitHubName and $GITHUB_TOKEN in the environment variables
