Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,109 +2,88 @@ version: 2.1
 jobs:
   build:
     docker:
-      - image: fr3akyphantom/droid-builder:focal
+      - image: fr3akyphantom/droid-builder:edge
     environment:
-      MANIFEST_BR: 'android-9.0' # Optional: State SHRP Manifest Branch. i.e., '9.0' or other
-      VENDOR: 'cherry_mobile' # State Product Vendor or Manufacturer
-      CODENAME: 'x930' # Device Codename
-      # GitHubMail: '' # Enter GitHub User EMail Address. Has been set in context.
-      # GitHubName: '' # Enter GitHub Username. Has been set in context.
-      ## Add the following Token in encrypted form inside CircleCI
-      # GITHUB_TOKEN: '' # GitHub OAuth Token, for release. Has been set in context.
-      Device_Tree: 'https://github.com/loveleyz/X930/' # The Full URL of DT
-      BUILDTYPE: 'eng' # Set as eng or userdebug
-      VER: '2.3'
-    working_directory: /home/builder/shrp/
+      # GitHubMail: "" # Git User Email Address
+      # GitHubName: "" # Git Username
+      # GITHUB_TOKEN: '' # MUST BE SECRET & PUT IN CIRCLECI PROJECT ENV VARS
+      VENDOR: 'cherry_mobile' # MANDATORY
+      CODENAME: 'x930' # MANDATORY
+      FLAVOR: 'userdebug' # MANDATORY
+    working_directory: /home/builder/skyhawk
     steps:
-    # - checkout
       - run:
-          name: Check if all env vars are set or not
+          name: AIO Build
           command: |
-            # Do not modify this part
-            if [[ -z ${Device_Tree} ]]; then
-              echo -e "\n Device Tree URL is not given.\n Can not proceed." && exit 1
-            elif [[ -z ${VENDOR} ]]; then
-              echo -e "\n Vendor Name not given." && exit 1
-            elif [[ -z ${CODENAME} ]]; then
-              echo -e "\n Device Codename not given." && exit 1
-            elif [[ -z ${BUILDTYPE} ]]; then
-              echo -e "\n Build Type, e.g., eng or userdebug is not set." && exit 1
-            fi
-            if [[ -z ${MANIFEST_BR} ]]; then
-              echo -e "\n Using Default Pie Manifest Branch."
-              MANIFEST_BR="android-9.0"
-            fi
-            if [[ -z $GitHubName ]]; then
-              echo -e "\n GitHub Username is not set." && exit 1
-            elif [[ -z $GitHubMail ]]; then
-              echo -e "\n GitHub E-mail Address is not set." && exit 1
-            fi
-            if [[ -z ${GITHUB_TOKEN} ]]; then
-              echo -e "\n GitHub OAuth Token not set. Can not Upload Built File on GitHub Releases."
-            fi
-      - run:
-          name: Create & Run a keep-alive shell
-          command: |
-            # Basic trick to ping every 5 minutes in the background
-            cat \<< EOF > /tmp/act.sh
-            #!/bin/bash
-            while true; do
-              echo -e "\n" && sleep 300
-            done
-            EOF
-            chmod a+x /tmp/act.sh
-      - run:
-          name: Repo Init and Sync
-          command: |
-            # Set Git Credential
+            # SANITY CHECKS
+            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
+            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
+            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
+            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
+            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
+            if [[ -z $FLAVOR ]]; then echo -e "Set as 'eng' or 'userdebug'." && exit 1; fi
+            # Set GitAuth Infos"
             git config --global user.email $GitHubMail
             git config --global user.name $GitHubName
-            git config --global color.ui true
             git config --global credential.helper store
-            echo -e "\n Initialize repo Command"
-            repo init -q -u https://github.com/SKYHAWK-Recovery-Project/platform_manifest_twrp_omni.git -b ${MANIFEST_BR} --depth 1
-            echo -e "\n Removing Unimportant Darwin-specific Files from syncing"
+            git config --global color.ui true
+           
+            cd /home/builder/skyhawk
+            
+            echo -e "Initializing minimal manifest repo sync..."
+            repo init --depth=1 -u git://github.com/SKYHAWK-Recovery-Project/platform_manifest_twrp_omni.git -b android-9.0
+            
+            echo -e "\nRemoving Unimportant Darwin-specific Files from syncing"
             cd .repo/manifests
-            sed -i '/darwin/d' default.xml
-            ( find . -type f -name '*.xml' | xargs sed -i '/darwin/d' ) || true
+            find . -type f -name '*.xml' | xargs sed -i '/darwin/d'
             git commit -a -m "Magic" || true
-            cd ../
-            sed -i '/darwin/d' manifest.xml
-            cd ../
-            echo -e "\n Syncing it up! Wait for a few minutes..."
-            /tmp/act.sh & repo sync -c -q --force-sync --no-clone-bundle --optimized-fetch --prune --no-tags -j$(nproc --all)
-      - run:
-          name: Clone Device tree and Stuff
-          command: |
-            # Clone DT
-            git clone ${Device_Tree} device/${VENDOR}/${CODENAME}
-            # Custom Patches are non-aligned, need to fix media0.patch & twres.patch
-            # Then apply using 'patch' command
-      - run:
-          name: Run Default Build
-          command: |
-            echo -e "\n Build process starting..."
+            cd ../ && sed -i '/darwin/d' manifest.xml && cd ../
+            
+            # Local manifests. Some builds fail if the file path does not exist.
+            mkdir -p .repo/local_manifests && cat \<<EOF > .repo/local_manifests/x930.xml
+            <?xml version="1.0" encoding="UTF-8"?>
+            <manifest>
+            <project path="device/cherry_mobile/x930" name="loveleyz/X930" revision="shrp-9.0" remote="github" />
+            </manifest>
+            EOF
+            
+            repo sync -c -q --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
+            
+            # Unshallow vendor_omni
+            repo forall vendor/omni -c "git fetch --unshallow omnirom android-9.0"
+            # Retain "roomservice: Do not overwrite existing repositories"
+            repo forall vendor/omni -c "git revert 718f4c2fd6890f5eaa2d4972b1c3f3f582b5da47 -Xtheirs --no-edit --no-commit"
+            # Retain "roomservice: Do not overwrite existing devices"
+            repo forall vendor/omni -c "git revert 380d19cea2857d5901d7e7163f65ccc66d7bbad7 -Xtheirs --no-edit --no-commit"
+            # Add those retains into local commit
+            repo forall vendor/omni -c "git commit -m 'Fix Build from forked/personal repos'"
+            echo -e "\nPreparing Delicious Lunch..."
             export ALLOW_MISSING_DEPENDENCIES=true
-            source build/envsetup.sh 2>&1 > /tmp/log.txt
-            lunch omni_${CODENAME}-${BUILDTYPE} 2>&1 >> /tmp/log.txt
-            /tmp/act.sh & make -j$(nproc --all) recoveryimage 2>&1 | sudo tee -api /tmp/log.txt
-            echo -e "\n CCache Stats"
-            ccache -s
-            mkdir release
-            cp out/target/product/${CODENAME}/SHRP*.zip release/
-            cp out/target/product/${CODENAME}/*.img release/ 
-      - run:
-          name: Release all built files
-          command: |
-            if [[ ! -z ${GITHUB_TOKEN} ]]; then
-              du -sh release/*
-              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "SkyHawk Recovery Project $(echo $VER)" -b "Latest Release for $(echo $CODENAME)" -c ${CIRCLE_SHA1} -delete v$(echo $VER) release/
-            else
-              echo -e "\n Files not uploaded due to absent of GITHUB_TOKEN as env variable"
-            fi
+            export LC_ALL="C"
+            source build/envsetup.sh
+            lunch omni_Flare_S8-userdebug
+            
+            # Keep the whole .repo/manifests folder
+            cp -a .repo/manifests $(pwd)/
+            echo "Cleaning up the .repo folder to slim down the build system"
+            rm -rf .repo
+            mkdir -p .repo && mv manifests .repo/ && ln -s .repo/manifests/default.xml .repo/manifest.xml
+            
+            export nowTime=$(date +%Y%m%d-%H%M)
+            echo -e "\nBuilding Started, Please wait patiently...\n"
+            make -j$(nproc --all) recoveryimage
+            echo "Ready to Deploy"
+            mkdir upload
+            export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
+            cp out/target/product/${CODENAME}/recovery.img upload/SHRP-${version}-${CODENAME}-$nowTime-Unofficial.img
+            cp out/target/product/${CODENAME}/*.img upload/
+            cp out/target/product/${CODENAME}/ramdisk* upload/
+            cp out/target/product/${CODENAME}/*.zip upload/
+            ls -lA upload/
+            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test SkyHawk Recovery Release for $(echo $CODENAME)" -b "SHRP $(echo $version)" -delete shrp_v${version} upload/
 workflows:
   version: 2
-  shrp-builder:
+  build_and_test:
     jobs:
       - build:
         filters:
